package com.alipay.hulu.shared.io.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alipay.hulu.shared.io.bean.RecordCaseInfo;

import com.alipay.hulu.shared.io.db.RecordCaseInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordCaseInfoDaoConfig;

    private final RecordCaseInfoDao recordCaseInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordCaseInfoDaoConfig = daoConfigMap.get(RecordCaseInfoDao.class).clone();
        recordCaseInfoDaoConfig.initIdentityScope(type);

        recordCaseInfoDao = new RecordCaseInfoDao(recordCaseInfoDaoConfig, this);

        registerDao(RecordCaseInfo.class, recordCaseInfoDao);
    }
    
    public void clear() {
        recordCaseInfoDaoConfig.clearIdentityScope();
    }

    public RecordCaseInfoDao getRecordCaseInfoDao() {
        return recordCaseInfoDao;
    }

}
